solution: RDFSharp.sln
script:
  - msbuild /p:Configuration=Release RDFSharp.sln
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./XUnitTestProject1/bin/Release/XUnitTestProject1.dll
