language: csharp
solution: RDFSharp.sln
install:
  - nuget restore RDFSharp.sln
  - nuget install xunit.runner.console -Version 2.2.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release RDFSharp.sln
  - mono ./testrunner/xunit.runner.console.2.2.0/tools/xunit.console.exe ./XunitFrameworkmanual/bin/Release/netcoreapp2.0/XunitFrameworkmanual.dll
